
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  namespace: default
  labels:
    app: user-management-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: user-management-app
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-nodeport
  namespace: default
  labels:
    app: user-management-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: user-management-app
